### ISSUE TITLE
python question

### ISSUE THREAD

**Issue by Neautrino** [Neautrino/python-questions#1]
Add python questions with answers

**Comment by nancy-singh10** [comment]
hey 
plz assign me this issue under hacktoberfest2023 
thanks

**Comment by subhashree9898** [comment]
Hey @Neautrino 
Please assign me this issue

**Comment by subhashree9898** [comment]
Hey @Neautrino 
Can you please merge the existing pull request if it's okay?

**Comment by abhaygzb15** [comment]
@Neautrino Hey!! It would be grateful for me if you could assign this issue to me under hactoberfest. Can I add snake game or Tower of Hanoi code for this repo under this issue ?

**Comment by MahakGautam2002** [comment]
Hey, I can write code for all python problem, so please assign this issue to me under hacktoberfest2023 tag.

**Comment by BEAST-PRINCE** [comment]
PR made for this issue. Please merge.

**Comment by Sebastianshrisunder** [comment]
Hey pls assign me this issue.
I would like to add more complex questions and solution to it.
Thanks.

**Comment by ShrutiKolla** [comment]
@Neautrino can you please assign this to me?

**Comment by Sebastianshrisunder** [comment]
Hey @Neautrino Can you please merge my pull request? Added Mergesort and An additional problem

**Comment by sayam12d** [comment]
kindly @Neautrino 
assign me  this under hactoberfest

**Comment by 35C4n0r** [comment]
@Neautrino I would also like to contribute.

**Comment by Akshada-26** [comment]
I would like to contribute

**Comment by Neautrino** [comment]
Merged all the PRs.

Kindly check your PR.
